### ISSUE TITLE
[Bug]Files with a code tree affect files without a code tree

### ISSUE THREAD

**Issue by actforjason** [halfbrained/cuda_breadcrumbs#61] opened 2022-10-15 13:00 UTC
`'sub'` is the code tree of menu.json, and readme.txt doesn't have code tree.
![image](https://user-images.githubusercontent.com/57058325/195987696-f52dc2de-1d20-452d-a344-e03baf4bec32.png)

**Comment by Alexey-T** [comment] 2022-10-15 14:31
Cannot confirm it yet. opened .txt file and json with code-tree. Do you have steps to repeat?

Post your config from settings/plugins.ini. 
Mine--
```
[breadcrumbs]
root_dir_source=0
show_root_parents=1
file_sort_type=ext
tilde_home=1
show_hidden_files=0
max_name_len=15
max_dirs_count=0
position_bottom=1
path_separator=
code_navigation=1
code_tree_height=0
```

@veksha @eltonfabricio10 @jairomartineza Maybe you can confirm?

**Comment by JairoMartinezA** [comment] 2022-10-16 02:54
Yes Alex, the issue happens, using a readme example, the tree updates in the video is related to my Notes.md file that I always use.

https://user-images.githubusercontent.com/5806694/196015623-1f5d2309-6e3a-465c-bed4-78fe8ec45d3a.mov

**Comment by eltonfabricio10** [comment] 2022-10-16 05:47
On Linux I cannot reproduce this.
But when you run the command "Show code-tree" from the menu, it open the empty "BreadCrumbs Tree".

**Comment by Alexey-T** [comment] 2022-10-16 10:29
Jairo, so you are clicking tab with .txt file but code-tree remains (from the old tab)?
can you attach your user.json here?

**Comment by JairoMartinezA** [comment] 2022-10-16 10:51
> Jairo, so you are clicking tab with .txt file but code-tree remains (from the old tab)?

Yes Alex
[user.json.zip](https://github.com/halfbrained/cuda_breadcrumbs/files/9794239/user.json.zip)

**Comment by veksha** [comment] 2022-10-19 22:16
@eltonfabricio10 wrote:
> On Linux I cannot reproduce this.

On Windows I cannot reproduce this.

> But when you run the command "Show code-tree" from the menu, it open the empty "BreadCrumbs Tree".

this bug I confirm.

https://user-images.githubusercontent.com/275333/196815023-68910409-d667-419b-a7ef-4b206e875865.mp4

**Comment by Alexey-T** [comment] 2022-10-19 22:26
hm, I cannot help wtih fixing the Breadcrumbs, but I will try to fix Cud's bug - when Cud did not update code-tree on tab switching to .txt file. if it's Cud bug. help me with repro, in the linked Cud's issue. https://github.com/Alexey-T/CudaText/issues/4459

**Comment by Alexey-T** [comment] 2022-10-20 00:10
@actforjason Update Breadcrumb plugin from AddonsManager. it is fixed. close the issue if Ok

**Comment by JairoMartinezA** [comment] 2022-10-20 02:07
First testing shows OK.

**Closed as completed** 2024-11-05 07:29 UTC
